### ISSUE TITLE
Why `$BigInt` is needed?

### ISSUE THREAD

**Issue by JounQin** [inspect-js/has-bigints#13]
```js
'use strict';

var $BigInt = typeof BigInt !== 'undefined' && BigInt;

module.exports = function hasNativeBigInts() {
	return typeof $BigInt === 'function'
		&& typeof BigInt === 'function'
		&& typeof $BigInt(42) === 'bigint' // eslint-disable-line no-magic-numbers
		&& typeof BigInt(42) === 'bigint'; // eslint-disable-line no-magic-numbers
};
```

vs

```js
'use strict';

module.exports = function hasNativeBigInts() {
	return typeof BigInt === 'function'
		&& typeof BigInt(42) === 'bigint'; // eslint-disable-line no-magic-numbers
};
```

**Comment by ljharb** [comment]
Because `delete global.BigInt` and `BigInt = whatever` are both things that could happen later.

**Comment by JounQin** [comment]
> Because `delete global.BigInt` and `BigInt = whatever` are both things that could happen later.

@ljharb I don't think it's related to my question? `$BigInt` could be changed as you said, so we should not check it at all.

**Comment by ljharb** [comment]
It’s impossible to protect against code that runs before you. The purpose of this code is to protect against code that runs after you.

**Comment by ljharb** [comment]
Specifically, the code ensures that the initial state of the world matches the runtime state of the world.

**Comment by JounQin** [comment]
@ljharb 

I understand your point, but

1. `$BigInt` runs on init, not runtime, so that check is useless
2. `BigInt` already covers runtime check, `$BigInt` is redundant again

**Comment by ljharb** [comment]
Right - I’m checking both. That the environment natively supports bigints, and that that support still exists at runtime.

**Comment by JounQin** [comment]
> Right - I’m checking both.

I'm not sure to understand why? It can be polyfilled before `has-bigints` been loaded. And why should we consider whether it's supported natively or polyfilled?

**Comment by ljharb** [comment]
Sure, if it's polyfilled first, there's no way to determine that, and that's fine.

However, BigInt *can't* be polyfilled - because of `typeof` - so the only thing worth knowing is if it's supported natively, and this package's purpose is to determine if it's supported natively, and is still at the time you call the function.

**Comment by JounQin** [comment]
> However, BigInt can't be polyfilled - because of `typeof`

Then the runtime check also confirms it by `typeof` already?

**Comment by ljharb** [comment]
Sure, that's true. However, I don't need to do the runtime check if the environment never supported it in the first place - so it's an optimization for that case.

**Comment by JounQin** [comment]
Is that really an optimization? You have 4 branches to check for the environment actually supports `BigInt` natively?

If you really want to optimize, shouldn't it be like:

```js
var supported = typeof BigInt === 'function' && typeof BigInt(42) === 'bigint'

module.exports = function hasNativeBigInts() {
  return supported
}
```

**Comment by ljharb** [comment]
The intention is to also fail when `globalThis.BigInt` isn't available and correct.

**Comment by JounQin** [comment]
> The intention is to also fail when `globalThis.BigInt` isn't available and correct.

When native `BigInt` is unavailable, the check already fails, no need to test runtime `globalThis.BigInt` at all?

**Comment by ljharb** [comment]
sure, that's what `&&` does. However, just because it's initially available doesn't mean it's available "now".

**Comment by JounQin** [comment]
What do you mean? The native part can be injected dynamically? If so, `$BigInt` is also incorrect??

When `$BigInt` fails, there is no need to test runtime `BigInt` at all if you want to **optimize**.

**Comment by ljharb** [comment]
I'm not sure how to explain it more clearly. Before the module is evaluated, either BigInt is natively available or not.

If not, the function always returns false.

After the module is evaluated, BigInt may _remain_ natively available, or not.

If not, the function returns false; if so, and if BigInt was initially natively available, the function returns true.

The only improvement I can see that could be made to this code is to check `$BigInt` at module level (wrapped in a try/catch) instead of in the function body.

Is there a reason you're so intensely interested in these 2 additional lines?

**Comment by JounQin** [comment]
> The only improvement I can see that could be made to this code is to check $BigInt at module level (wrapped in a try/catch) instead of in the function body.

That's what my proposal doing? It meets all your expectation.

```js
var supported = typeof BigInt === 'function' && typeof BigInt(42) === 'bigint'

module.exports = function hasNativeBigInts() {
  return supported
}
```

> Is there a reason you're so intensely interested in these 2 additional lines?

I'm just trying understand the reason why codes are written like this, which is absolutely not an optimization: 4 branches for environment supports `BigInt` natively.

How could it be possible that `$BigInt` is unavailable before evaluated but available on runtime?

**Comment by ljharb** [comment]
1. Your suggestion would fail on module evaluation if earlier-run code had installed a global `BigInt` that throws
1. Your suggestion does not fail when someone has done `delete globalThis.BigInt` after evaluating this module..

**Comment by JounQin** [comment]
> 1. Your suggestion would fail on module evaluation if earlier-run code had installed a global `BigInt` that throws
> 2. Your suggestion does not fail when someone has done `delete globalThis.BigInt` after evaluating this module..

Thanks, they seem making sense to me now. I'll try to figure out.
